### ISSUE TITLE
nextCloud Version 20 update?

### ISSUE THREAD

**Issue by BloodyIron** [pawelrojek/nextcloud-drawio#127] opened 2020-10-04 03:47 UTC
Hey so any word on when this will have full compatibility with nextCloud 20? Really loving this app and literally broadcasting upgrading to nextCloud 20 as I type this lol. Thanks!

**Comment by s-rosenfeld** [comment] 2020-10-05 04:56
+ my vote

**Comment by welrbraga** [comment] 2020-10-07 03:20
+ 1

**Comment by dbarreda** [comment] 2020-10-10 01:19
The only issue I have seen so far is that opening drawio xml files from the "recommended files" dashboard doesn't open the file.

**Comment by plinss** [comment] 2020-10-16 19:02
Using Firefox or Chrome I get a blank page when opening a drawing file. The console has the error:

    Content Security Policy: The page’s settings blocked the loading of a resource at https://{domain}/ (“frame-src”).

Looks like the app needs to update the CSP header for Nextcloud (or the API for doing so has changed).

Note that I'm using a self-hosted draw.io server on a different sub-domain (e.g. Nextcloud is at https://cloud.{domain} and Draw.io is at https://draw.{domain}). Worked fine on NC 19.

**Comment by vahem2lu** [comment] 2020-10-22 08:01
`php occ app:check-code drawio`
gives a lot of errors, so NC20 support here needed as well.

**Comment by l4b4r4b4b4** [comment] 2020-10-27 00:27
+ 150 ;)

**Comment by gb-123-git** [comment] 2020-10-30 11:48
+1

**Comment by turin331** [comment] 2020-11-11 13:10
+1 on this from me. The issue i currently have with the plugin is that i cannot make a new xml file on the web interface. The page just loads for ever. But if i make an xml diagram from my desktop and put it on nextcloud the editor open normally.  SO an update is needed.

**Comment by arnowelzel** [comment] 2020-11-29 07:28
> 
> 
> `php occ app:check-code drawio`
> gives a lot of errors, so NC20 support here needed as well.

I just create a PR to fix these errors. I'll also try to fix any remaining problems for NC20 as needed.

**Comment by Schmuuu** [comment] 2020-11-29 16:36
> If anyone needs a ZIP file to update the application manually before there is a new official release, just let me know.
I guess a zip file could be helpful for a lot of us. With PRs (from early this year) still being open, it could take a while since your PR is merged.
And thank you so much for your efforts! Only the Drawio app was holding me back from updating to NC20.

**Comment by arnowelzel** [comment] 2020-11-29 16:48
You can find the ZIP file here: https://nextcloud.0x0c.de/s/w2KW4AZRBeR4585

**Comment by mariusbolik** [comment] 2020-12-02 07:59
@arnowelzel Thank you very much for this update. It work's very well in Chrome and Safari. But in Brave Browser I get the following error: 
<img width="1182" alt="Bildschirmfoto 2020-12-02 um 08 47 30" src="https://user-images.githubusercontent.com/39862171/100844324-063a3880-347c-11eb-973f-19598478d343.png">
<img width="558" alt="Bildschirmfoto 2020-12-02 um 08 47 01" src="https://user-images.githubusercontent.com/39862171/100844338-09cdbf80-347c-11eb-9467-b84a84f0c7ed.png">
Can you please try it with Brave Browser and tell me if you have the same problem?

**Comment by arnowelzel** [comment] 2020-12-02 08:38
Can you please check first, if https://app.diagrams.net/ works for you in Brave Browser?

**Comment by mariusbolik** [comment] 2020-12-02 08:45
> Can you please check first, if https://app.diagrams.net/ works for you in Brave Browser?

Yes, it works without any problems :)

**Comment by pawelrojek** [comment] 2020-12-02 23:17
Is this working for you?

![image](https://user-images.githubusercontent.com/20641546/100942268-55737e00-34fb-11eb-8a1b-706a24fcef4b.png)

When I click on the drawio file the Preview Window appears (instead of opening the file in draw.io):
![image](https://user-images.githubusercontent.com/20641546/100943033-b485c280-34fc-11eb-82bf-e812497b4152.png)


This is the reason why I haven't updated and released the App yet. I didn't have time to dig into this.

But, since people seems to be "impatient" I'm gonna release this version we got right now with "Known Issues".

**Comment by arnowelzel** [comment] 2020-12-03 01:30
I just checked it with Brave Browser Version 1.17.73 Chromium: 87.0.4280.67 (Offizieller Build) (64-Bit).

So far I could not find any issues - Draw.io works fine here:

![grafik](https://user-images.githubusercontent.com/6613614/100951672-4e566b00-350f-11eb-9811-9018f649dc78.png)

I also can not confirm the XML problem. Did you forget to enable the option "Associate XML files with Draw.io?" in the additional settings in Nextcloud?

**Comment by arnowelzel** [comment] 2020-12-03 01:35
In addition: If anyone needs a test account on my Nexcloud development server (which runs the latest stable version of Nextcloud) for reference, send me an e-mail.

**Comment by mariusbolik** [comment] 2020-12-03 08:31
> I just checked it with Brave Browser Version 1.17.73 (64 bit version running in Windows 10 Pro).
> 
> So far I could not find any issues - Draw.io works fine here:
> 
> ![grafik](https://user-images.githubusercontent.com/6613614/100951672-4e566b00-350f-11eb-9811-9018f649dc78.png)
> 
> I also can not confirm the XML problem. Did you forget to enable the option "Associate XML files with Draw.io?" in the additional settings in Nextcloud?

Thank you for looking into this, Arno. I figured out that I have to disable the tracking protection for my Nextcloud by clicking on the Brave Logo on the right side of the search bar :)

**Comment by arnowelzel** [comment] 2020-12-03 09:23
@mariusbolik thanks for the feedback

About the XML issue - I did not realize, that this was about opening an XML file from the Dashboard app. When using the ".drawio" extension this does not happen. In this case, the file browser is opened and the file is selected there.

This may be a bug of the "Dashboard" app which should be reported there as well.

**Comment by arnowelzel** [comment] 2020-12-03 18:24
@pawelrojek The problem is the "recommendations" app. This app is responsible for the "Recommended files" box in the dashboard as well as the "recommendations" on top of the Nextcloud file manager. It seems this app just ignores MIME types - neither XML nor .drawio works as expected.

I created a new issue for this: https://github.com/nextcloud/recommendations/issues/340

However, we should release Draw.io anyway - whatever this problem is, we should not wait with the update, since everything else works just fine.

**Comment by pawelrojek** [comment] 2020-12-04 01:32
@arnowelzel
I agree. It's on the App Store now.

**Comment by turin331** [comment] 2020-12-21 09:28
Can confirm that the "new diagram" issue is fixed with the latest update.

**Closed** 2021-03-10 21:34 UTC
